export const FETCH_REVIEWS_PENDING = 'review/FETCH_REVIEWS_PENDING';
export const FETCH_REVIEWS_SUCCESS = 'review/FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAIL = 'review/FETCH_REVIEWS_FAIL';
export const CHANGE_DISPLAY_MODE = 'review/CHANGE_DISPLAY_MODE';
export const UPDATE_REVIEW_PENDING = 'review/UPDATE_REVIEW_PENDING';
export const UPDATE_REVIEW_SUCCESS = 'review/UPDATE_REVIEW_SUCCESS';
export const DELETE_REVIEW_SUCCESS = 'review/DELETE_REVIEW_SUCCESS';