export const FETCH_REVIEWS_PENDING = 'review/FETCH_REVIEWS_PENDING';
export const FETCH_REVIEWS_SUCCESS = 'review/FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAIL = 'review/FETCH_REVIEWS_FAIL';