export const FETCH_REVIEWS_PENDING = 'review/FETCH_REVIEWS_PENDING';
export const FETCH_REVIEWS_SUCCESS = 'review/FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAIL = 'review/FETCH_REVIEWS_FAIL';
export const CHANGE_DISPLAY_MODE = 'review/CHANGE_DISPLAY_MODE';